# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-18 12:36
from __future__ import unicode_literals
import random

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('mapstore2_adapter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapstoreresource',
            name='id',
            field=models.BigIntegerField(
                default=random.randint(1000, 99999), primary_key=True, serialize=False, unique=True),
        ),
    ]
